title: Skandan C Yalagach

description: From Math to Machines.

author:
  name: Skandan C Yalagach
  email: skandanyalagach@gmail.com
  uri: https://skandanyal.github.io

social:
  name: Skandan C Yalagach
  links:
    - https://github.com/skandanyal
    - https://linkedin.com/in/skandan-cy/

baseurl: ""
url: "https://skandanyal.github.io"

markdown: kramdown
highlighter: rouge

permalink: /from_math_to_machines/:title/

future: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - metadata.json
  - index.tsx
  - App.tsx
  - data.ts
  - types.ts
  - components/

collections:
  notes:
    output: true
    permalink: /notes/:name/

kramdown:
  math_engine: mathjax
